rails/config/routes.rb
BusinessApp::Application.routes.draw do
  resources :businesses
  resources :sessions, only: [:new, :create, :destroy]
  resources :deals

	match '/newpromo', to: 'deals#new'
	match 'promos/:id', to: 'deals#show'
	match 'promos/:id/edit', to: 'deals#edit'

 	match 'businesses/:id/stats' => 'businesses#stats', :as => :stats_business
  match 'businesses/:id/stats_update' => 'businesses#stats_update', as: :stats_update_business
 	
  match '/signup',  to: 'businesses#new'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
 
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/stats',   to: 'static_pages#stats'

end

rails/app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_filter :signed_in_business, 	only: [:show, :edit, :update, :index, :destroy]
	before_filter :correct_business, 		only: [:show, :edit, :update, :destroy]
	before_filter :session_created, only: [:new, :create]
	#May be dangerous to allow all users to destroy?
	#before_filter :admin_user,					only: :destroy 

	def stats
		@business = Business.find(params[:id])

    # heatmap manipulations
    @start_date = Coordinate.minimum("time").getlocal.strftime("%m/%d/%Y %I:%M %p")
    @end_date = Coordinate.maximum("time").getlocal.strftime("%m/%d/%Y %I:%M %p")

		raw_data = JSON.parse(Coordinate.select("latitude, longitude").to_json)
    raw_data.each do |d|
      d["count"] = "1"
    end
    # formatting for javascript
    @data = raw_data.to_json.gsub('"', '').gsub('latitude', 'lat').gsub('longitude', 'lng')
    @size = raw_data.count
	end

  def stats_update
    @business = Business.find(params[:id])
    @start_date = params[:time][:start]
    @end_date = params[:time][:end]

    zone = Time.zone.now.formatted_offset(colon=false)
    start_strp = DateTime.strptime(params[:time][:start] + zone, '%m/%d/%Y %I:%M %p%Z').utc.to_s(:db)
    end_strp = DateTime.strptime(params[:time][:end] + zone, '%m/%d/%Y %I:%M %p%Z').utc.to_s(:db)

    raw_data = JSON.parse(Coordinate.select("latitude, longitude").
      where("time >= '#{start_strp}' and time <= '#{end_strp}'").to_json)
    raw_data.each do |d|
      d["count"] = "1"
    end
    # formatting for javascript
    @data = raw_data.to_json.gsub('"', '').gsub('latitude', 'lat').gsub('longitude', 'lng')
    @size = raw_data.count

    render 'stats'
  end

  def show
    @business = Business.find(params[:id])
		@deals = @business.deals.find(:all, conditions: {isEvent: false}).paginate(page: params[:deals_page], per_page: 5)
    @events = @business.deals.find(:all, conditions: {isEvent: true}).paginate(page: params[:events_page], per_page: 5)
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(params[:business])
    if @business.save
			sign_in @business
      flash[:success] = "Welcome to Around The Corner!"
      redirect_to @business
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    unless params[:cancel].blank?
      redirect_to @business
      return
    end

    if params[:business][:password].blank?
      @business.update_attribute(:name, params[:business][:name])
      @business.update_attribute(:email, params[:business][:email])
      @business.update_attribute(:address, params[:business][:address])
      @business.update_attribute(:phoneNumber, params[:business][:phoneNumber])
      @business.update_attribute(:imageURL, params[:business][:imageURL])
      @business.update_attribute(:image, params[:business][:image])
      @business.update_attribute(:image_delete, params[:business][:image_delete])
      flash[:success] = "Profile updated"
      sign_in @business
      redirect_to @business
    else
      if @business.update_attributes(params[:business])
        flash[:success] = "Profile updated"
        sign_in @business
        redirect_to @business
      else
        render 'edit'
      end
    end
  end
  
  def index
    if current_business.admin?
      @businesses = Business.all
    end
  end
  
  def destroy
		# ADD CODE TO PREVENT ADMIN FROM DELETING HIMSELF OR OTHER ADMIN
	  Business.find(params[:id]).destroy
    flash[:success] = "Business destroyed."
    redirect_to businesses_url
	end

	private
		def correct_business
			@business = Business.find(params[:id])
			redirect_to(root_path) unless (current_business?(@business) || current_business.admin?)
		rescue
			redirect_to(root_path)
		end

		def admin_user
      redirect_to(root_path) unless current_business.admin?
    end
end

rails/app/helpers/businesses_helper.rb
module BusinessesHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(business, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(business.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: business.name, class: "gravatar")
  end
end

rails/app/views/businesses/edit.html.erb
<% content_for :head do %>
	<%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?libraries=places&sensor=true" %>
	<%= javascript_include_tag "google-places-autocomplete.js" %>
<% end %>

<% provide(:title, "Edit Profile") %> 
<% provide(:subtitle, "Update Your Profile") %>

<div class="container jumbotron">
	<div class="row">
		<%= form_for @business, :html => { :multipart => true } do |f| %>
			<%= render 'shared/business_error_messages' %>
			<div class="span6">
		    <%= f.label :name %>
		    <%= f.text_field :name %>

		    <%= f.label :email %>
		    <%= f.text_field :email %>

		    <%= f.label :password %>
		    <%= f.password_field :password %>

		    <%= f.label :password_confirmation, "Confirm Password" %>
		    <%= f.password_field :password_confirmation %>
			</div>
			<div class="span6">
				<div id='address_input'>
			    	<%= f.label :address, "Address" %>
					<%= f.hidden_field :address %>
					<%= text_field_tag :location_search, nil, type: "text", value: @business.address, placeholder: "Start typing a place name..." %>
			    </div>

			    <div id='map-canvas'></div>
				
				<%= f.label :"Phone Number" %>
				<%= f.text_field :phoneNumber %>

		    <%= f.label :image, "Or Upload Image" %>
		    <%= f.file_field :image %>
			<% unless @business.image_file_size.blank? %>
	          <p>
	          	(Current upload -- Check box to delete:<br />
	          	<%= f.check_box :image_delete %> <%= @business.image_file_name %>)
	          </p>
	        <% end %>
				
		    <br><br>
		    <%= f.submit "Save changes", class: "btn btn-primary" %>
		    <%= submit_tag 'Cancel', :name => 'cancel', class: "btn btn-primary", style: "margin-left: 20px;" %>
			</div>
			<!--
			<div class="span4">	
				<%= f.label :imageURL, "Image URL" %>
		    <%= f.text_field :imageURL %>

		  </div>-->
		<% end %>
	</div>
</div>

rails/app/views/businesses/index.html.erb
<% provide(:title, 'All Businesses') %>
<% provide(:subtitle, 'All Businesses') %>

<div class="container jumbotron">

<% if current_business.admin? then %>
  <%= link_to "<< View profile", current_business %>
<% end %>

<ul class="businesses">
  <% @businesses.each do |business| %>
    <li>
      <%= link_to business.name, business %>
      (<%= business.deals.all.size %>)
      <% if current_business.admin? && !current_business?(business) %>
        | <%= link_to "delete", business, method: :delete,
                                      data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

</div>

rails/app/views/businesses/new.html.erb
<% provide(:title, 'Sign Up') %>
<% provide(:subtitle, 'Sign Up') %>

<div class="container jumbotron">
  <div class="row">
	    <div class="span6">
				<%= form_for(@business) do |f| %>
					<%= render 'shared/business_error_messages' %>

					<%= f.label :name, "Name or Organization" %>
					<%= f.text_field :name %>

					<%= f.label :email %>
					<%= f.text_field :email %>

					<%= f.label :password %>
					<%= f.password_field :password %>

					<%= f.label :password_confirmation, "Confirm Password" %>
					<%= f.password_field :password_confirmation %>

					<br>

					<%= f.submit "Create my account", class: "btn btn-primary" %>
				<% end %>
				<p>Already a user? <%= link_to "Sign in now!", signin_path %></p>
	    </div>
	  	<%= render 'shared/summary_messages' %>
	</div>
</div>

rails/app/views/businesses/show.html.erb
<% provide(:title, @business.name) %>
<% provide(:subtitle, "Dashboard") %>

<div class="container jumbotron">
<div class="row">
  <aside class="span4">
    <% if current_business.admin? && !current_business?(@business) then %>
      <%= link_to "<< View all businesses", businesses_path %>
    <% end %>
    <section>
      <h1><%= @business.name %></h1>
	  <% unless @business.imageURL.blank? %> 
		<img src=<%= @business.imageURL %> width="200px", height="200px">
		<br><br>
	  <% end %>
	  <% unless @business.image_file_name.blank? %> 
		<%= image_tag @business.image.url(:medium) %>
		<br><br>
	  <% end %>
	  <p><%= link_to "Edit profile", edit_business_path(@business) %></p>
	  <p><%= link_to "View customer statistics", stats_business_path(@business) %></p>
			<% unless current_business.admin? then %>
				<p><a href="/newpromo" class="btn btn-primary">Create promotion</a></p>
			<% end %>
    </section>
  </aside>
	<% unless @business.admin? then %>
		<div class="span4">
		  <h3> Your Events: </h3>
		  <% if @business.deals.any? %>
			  <ol>
				  <% @events.each do |d| %>
					  <% if d.title && d.isEvent then %>
						  <li>
								<a href="/promos/<%= d.id %>"><%= d.title %></a>
                <i>Posted <%= time_ago_in_words(d.created_at) %> ago.</i>
								<a href="/promos/<%= d.id %>/edit">Edit</a>
                <% if current_business.admin? || current_business?(@business) then %>
                  <%= link_to "Delete", d, method: :delete,
                                                      data: { confirm: "You sure?" },
                                                      title: d.title %>
                <% end %>
              </li>
					  <% end %>
				  <% end %>
			  </ol>
			  <% if @events.total_pages > 1 %>
				<p>Page <%= @events.current_page %>/<%= @events.total_pages %></p>
			  <% end %>
			  <%= render(partial: 'shared/business_page_nav', 
		  	  	locals: {page: @events, param_name: :events_page}) %>
		  <% end %>
		</div>
		<div class="span4">
		 	<h3> Your Deals: </h3>
		 	<% if @business.deals.any? %>
		 	<ol>
			  	<% @deals.each do |d| %>
				  	<% if d.title && !d.isEvent then %>
					  	<li>
								<a href="/promos/<%= d.id %>"><%= d.title %></a>
               	<i>Posted <%= time_ago_in_words(d.created_at) %> ago.</i>
								<a href="/promos/<%= d.id %>/edit">Edit</a>
               	<% if current_business.admin? || current_business?(@business) then %>
                 	<%= link_to "Delete", d, method: :delete,
                   	                                  data: { confirm: "You sure?" },
                     	                                title: d.title %>
               	<% end %>
             	</li>
				  	<% end %>
			  	<% end %>
		  	</ol>
		  	<% if @deals.total_pages > 1 %>
				<p>Page <%= @deals.current_page %>/<%= @deals.total_pages %></p>
			  <% end %>
		  	<%= render(partial: 'shared/business_page_nav', 
		  	  	locals: {page: @deals, param_name: :deals_page}) %>
		 	<% end %>
		</div>
	<% else %>  
		<div class="span6"
		  <h3> Administrative Console </h3>
		  <h4><%= link_to "Manage businesses unique to site", businesses_path %></h4>
		  <h4><%= link_to "Site statistics", stats_path %></h4>
		</div>
	<% end %>
</div>
</div>

rails/app/views/businesses/stats.html.erb
<% content_for :head do %>
  	<%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false" %>
  	<%= stylesheet_link_tag "bootstrap-datetimepicker.min.css" %>
  	<%= javascript_include_tag "bootstrap-datetimepicker.min.js" %>
	<%= javascript_include_tag "stats/heatmap.js" %>
	<%= javascript_include_tag "stats/heatmap-gmaps.js" %>
<% end %>

<% provide(:title, "Customer Statistics") %>
<% provide(:subtitle, "Customer Statistics") %>

<div class="container jumbotron">
	<div class="row">
		<aside class="span4">
			<p><%= link_to "<< View all promotions", business_path(@business) %></p>
		    <h1><%= @business.name %></h1>
			  <% unless @business.imageURL.blank? %> 
				<img src=<%= @business.imageURL %> width="200px", height="200px">
				<br><br>
			  <% end %>
			  <% unless @business.image_file_name.blank? %> 
				<%= image_tag @business.image.url(:medium) %>
				<br><br>
			  <% end %>
		</aside>
		<div class="span6">
	        <div>
	        	<h4> Client Location Activity</h4>
	            <div id="heatmapArea" class="well" style="width:610px;padding:0;height:400px;cursor:pointer;position:relative;">
	            </div>
	            <p class="lead">Number of data points displayed: <%= @size %></p>
	        </div>
	        <%= form_for :time, url: "stats_update" do |f| %>
				<div class="well well-small span4">
					Start date:
				  	<div id="start" class="input-append">
				    	<input id="time_start" name="time[start]" data-format="MM/dd/yyyy HH:mm PP" type="text" value="<%= @start_date %>"></input>
				    	<span class="add-on">
					      	<i data-time-icon="icon-time" data-date-icon="icon-calendar">
					      	</i>
				    	</span>
				  	</div>
				  	End date:
				  	<div id="end" class="input-append">
				    	<input id="time_end" name="time[end]" data-format="MM/dd/yyyy HH:mm PP" type="text" value="<%= @end_date %>"></input>
				    	<span class="add-on">
					      	<i data-time-icon="icon-time" data-date-icon="icon-calendar">
					      	</i>
				    	</span>
				  	</div>
				</div>
				<script type="text/javascript">
				  	$(function() {
				    	$('#start').datetimepicker({
				      		language: 'en',
				      		pick12HourFormat: true,
				      		pickSeconds: false
				    	});
				    	$('#end').datetimepicker({
				    		language: 'en',
				      		pick12HourFormat: true,
				      		pickSeconds: false
				    	})
				  	});
				</script>
				<div class="span1">
					<%= f.submit "Update Map", class: "btn btn-primary" %>
				</div>
			<% end %>
	    </div>
		<!-- /container -->
		 <script type="text/javascript">
	        !function($){
	            $(function(){
	                window.prettyPrint && prettyPrint();
	    // lat & lng for Stanford campus
	    var myLatlng = new google.maps.LatLng(37.427502, -122.170286);

	    var myOptions = {
	      zoom: 14,
	      center: myLatlng,
	      mapTypeId: google.maps.MapTypeId.ROADMAP,
	      disableDefaultUI: false,
	      scrollwheel: true,
	      draggable: true,
	      navigationControl: true,
	      mapTypeControl: false,
	      scaleControl: true,
	      disableDoubleClickZoom: false
	    };
	    var map = new google.maps.Map($("#heatmapArea")[0], myOptions);
	    
	    var heatmap = new HeatmapOverlay(map, {
	        "radius":10,
	        "visible":true, 
	        "opacity":60
	    });
	  
	    var testData={
	            max: 5,
	            data: <%= @data %>
	        };

	    // this is important, because if you set the data set too early, the latlng/pixel projection doesn't work
	    google.maps.event.addListenerOnce(map, "idle", function(){
	        heatmap.setDataSet(testData);
	    });

	            });
	        }(window.jQuery)
	    </script>
	</div>
</div>