rails/config/routes.rb
BusinessApp::Application.routes.draw do
  resources :businesses
  resources :sessions, only: [:new, :create, :destroy]
  resources :deals

	match '/newpromo', to: 'deals#new'
	match 'promos/:id', to: 'deals#show'
	match 'promos/:id/edit', to: 'deals#edit'

 	match 'businesses/:id/stats' => 'businesses#stats', :as => :stats_business
  match 'businesses/:id/stats_update' => 'businesses#stats_update', as: :stats_update_business
 	
  match '/signup',  to: 'businesses#new'

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
 
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/stats',   to: 'static_pages#stats'

end

rails/app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
	  <footer>
	    <p class="pull-left"> 
	    	<%= link_to "About Us", about_path %> 
	    	&middot; <%= link_to "Contact Us", contact_path %>
	    </p>
	    <p class="pull-right">&copy; 2013 Around The Corner, Inc.</p> 
	  </footer>
  </div>
</div>

rails/app/views/layouts/_header.html.erb
<header id="header" class ="masthead">
	<div class="container">
		<div id="header-logo">
			<a href="/"><img src="/assets/new_logo.png" alt="logo", width="70px"></a>
			<span id="company-name">Around The Corner</span>
		</div>

		<% if signed_in? %>
			<div class="navbar"> 
      	<div>
        	<ul class="nav pull-right">
          	<li class="dropdown">
            	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_business.name %><b class="caret"></b></a>
            	<ul class="dropdown-menu">
              	<li class="nav-header">Your Account</li>
              	<li><%= link_to "View profile", current_business %></li>
              	<li><%= link_to "Edit profile", edit_business_path(current_business) %></li>
								<li><%= link_to "Help", help_path %></li>
              	<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
								<!--
              	<li class="nav-header">Your Customers</li>
              	<li><%= link_to "Profile", current_business %></li>
              	<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
								-->
            	</ul>
          	</li>
        	</ul>
      	</div>
    	</div>
		<% else %>
			<div id="header-navbar" class="navbar">
				<form class="navbar-form pull-right" method="post" action="/sessions">
					<input type="text" name="session[email]" placeholder="Email">
					<input id="password_signin" type="password" name="session[password]" placeholder="Password">
					<button type="submit" class="btn">Sign in</button>
				</form>
			</div>
		<% end %>
	</div>
</header>

rails/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

rails/app/views/layouts/_subheader.html.erb
<% if !(yield(:subtitle).blank?) %>
	<div id="subheader">
		<div class="container">
			<div class="row">
				<div class="subheader-text span12">
					<h1><%= full_subtitle(yield(:subtitle)) %></h1>
				</div>
			</div>
		</div>
	</div>
<% end %>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

		<%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag 'favicon.png?v=2' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    
    <%= yield :head %>

    <%= analytics_init if Rails.env.production? %>
  </head>
  <body style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif;">
    <%= render 'layouts/header' %>
		<%= render 'layouts/subheader' %>
    <div class="container">
			<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
			<div style="min-height: 403px">
    <%= yield %>
		</div>
    <%= render 'layouts/footer' %>
  </body>
</html>